name: "Close stale PRs"

permissions:
  pull-requests: write
  issues: write

on:
  schedule:
    - cron: "55 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-stale: 30
          days-before-issue-stale: -1
          days-before-close: 7
          exempt-pr-labels: pinned,security
